### PR TITLE
Initial working build of the Parallel Performance AT Catalogue

### PR DESCRIPTION
**Pull request by denis-zahariev**

### CODE REVIEW

**Review by seiferma — CHANGES_REQUESTED** [review]
I upgraded the used build infrastructure tools to the latest version. That made the build work.

However, I ask you to change the URLs used in the target platform definition to our [new update sites](https://updatesite.palladio-simulator.com/) before we have another look into your PR.

Please also fix the link to architectural templates in the readme file.

**Review by seiferma — APPROVED** [review]
The PR looks good to me from a formal point of view now. However, I have no glue whether the content is useful or not. But I do not think that this should be a blocker for merging to master because this is some sort of incubation project.

If it is not an incubation project, @marfraTUC should have another look on it.

**Review by marfraTUC — APPROVED** [review]
Looks good to me :)

**Comment by marfraTUC** [comment]
@seiferma I guess thats it right? I can accept and merge the pull request right?

**Comment by seiferma** [comment]
Sure, go on ;)

**Pull request merged**
